classDiagram
direction LR
    TBM908 "1" *-- "1" HS
    TBM908 "1" *-- "*" HSphysicalTBMcomponents
    class HS {
	    +bool paxOrPilotActivates
	    +bool inFlight
	    +float ampHoursRemaining
    }

    class Requirements {
	    note "FD=FltDir, AP=autopilot, YD=YawDampener, AT=AutoThrottle, XPDR=transponder=~7700"
	    -data FD
	    -data AP
	    -data YD
	    -data AT
	    -data airdata
	    -bool config-FD,AP,AT,XPDR
	    -bool foundFAAapprovedAirportOrRW
    }

    class AFCS {
    }

    class FMS {
    }

    class Databases {
    }

    class FADEC {
    }

    class `Comms-Audio-XPDR` {
    }

    class WeatherData {
    }

    class RadarAltimeter {
    }

    class Fuel {
    }

    class WoW {
    }
    
    class HSphysicalTBMcomponents {
	    +bool rudder
	    +bool elevator
	    +bool aileron
	    +bool flaps
	    +bool brakes
	    +bool landingGrar
	    +bool landingLight
    }

	note "Daher (inc HS (HomeSafe)) TBM980.pdf"

    HS "1" ..> "*" Requirements : evaluates
    HS "1" ..> "*" HSphysicalTBMcomponents : checks, evaluates, conforms
    HS "1" o-- "1" AFCS
    HS "1" o-- "1" FMS
    HS "1" o-- "1" Databases
    HS "1" o-- "1" FADEC
    HS "1" o-- "1" Comms-Audio-XPDR
    HS "1" o-- "1" WeatherData
    HS "1" o-- "1" RadarAltimeter
    HS "1" o-- "1" Fuel
    HS "1" o-- "1" WoW 



